export const scopesArray = [
  "create-products",
  "list-products",
  "update-products",
  "delete-products",
  "create-banners",
  "list-banners",
  "update-banners",
  "delete-banners",
  "create-category",
  "list-category",
  "update-category",
  "delete-category",
  "create-brand",
  "list-brand",
  "update-brand",
  "delete-brand",
];
